import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import Script from 'next/script'
import ScanbotDemoScannerComponent from './scanbot-demo-scanner.component'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isScriptLoaded, setIsScriptLoaded] = useState(false)
  const [imageData, setImageData] = useState(null)

  return (
    <>
      <Head>
        <title>Scanner Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <Script src="/ScanbotSDK.min.js" onReady={() => {setIsScriptLoaded(true)}} />

        {isScriptLoaded && (
            <ScanbotDemoScannerComponent
                //handleBarcode={(barcodeValue) => {alert(barcodeValue)}}
                handleDocument={(imgData) => {setImageData(imgData)}}
            />
        )}

        {imageData && (
            <img style={{width: 300}} src={imageData} alt={''} />
        )}

      </main>
    </>
  )
}
